name: VUnit with GHDL (LLVM backend)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  vunit-ghdl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt install -y git build-essential llvm-14 llvm-14-dev llvm-14-tools zlib1g-dev gnat

    - name: Build and install GHDL with LLVM backend
      run: |
        git clone https://github.com/ghdl/ghdl.git
        cd ghdl
        ./configure --with-llvm-config=llvm-config-14
        make
        sudo make install
        cd ..
        ghdl --version

    - name: Install VUnit
      run: pip install vunit_hdl

    - name: Run VUnit tests
      run: python run.py
